---
title: "assignment_5"
format: gfm
editor: visual
---

library(tidyverse)

library(knitr)

library(gapminder)


# **Assignment 5: Data transformation and visualization - Part 2**


## Exercise 1. Trends in land value

housing <- read_csv("https://raw.githubusercontent.com/nt246/NTRES-6100-data-science/master/datasets/landdata_states.csv")
housing %>%
  head() %>% 
  kable()
  
housing <- read_csv("https://raw.githubusercontent.com/nt246/NTRES-6100-data-science/master/datasets/landdata_states.csv")


### 1.1 Washington DC was not assigned to a region in this dataset. According to the United States Census Bureau, however, DC is part of the South region. Here:

housing_updated <- housing %>%
  mutate(region = ifelse(State == "DC", "South", region))
housing_subset <- housing_updated %>%
  select(State, Date, Land.Value, region)
dc_records <- housing_subset %>%
  filter(State == "DC")
n_dc_records <- nrow(dc_records)
cat("Number of DC records:", n_dc_records, "\n")
dc_records %>%
  head() %>%
  kable()


dc_records <- housing %>%
  mutate(region = ifelse(State == "DC", "South", region)) %>%
  filter(State == "DC") %>%
  select(region, State, Land.Value, Date)
dc_records %>%
  head(6) %>%
  kable()


### 1.2 Generate a tibble/dataframe that summarizes the mean land value of each region at each time point and show its first 6 lines.


housing_updated <- housing %>%
  mutate(region = ifelse(State == "DC", "South", region))

mean_land_values <- housing_updated %>%
  group_by(region, Date) %>%
  summarize(mean_land_value = mean(Land.Value, na.rm = TRUE), .groups = 'drop')
mean_land_values %>%
  head(6) %>%
  kable()

### 1.3 Using the tibble/dataframe from 1.2, plot the trend in mean land value of each region through time.

mean_land_values <- housing_updated %>%
  group_by(region, Date) %>%
  summarize(mean_land_value = mean(Land.Value, na.rm = TRUE), .groups = "drop")
  
housing_fixed <- housing %>%
  mutate(region = ifelse(State == "DC", "South", region))
  
mean_land_by_region <- housing_fixed %>%
  group_by(region, Date) %>%
  summarize(mean_land_value = mean(Land.Value, na.rm = TRUE), .groups = 'drop')
  
  
ggplot(mean_land_by_region, aes(x = Date, y = mean_land_value, color = region)) +
  geom_smooth(se = FALSE, size = 1.2) +
  labs(
    x = "Date",
    y = "Mean Land Value",
    color = "Region"
  ) +
  theme_minimal() +
  theme(
    text = element_text(size = 12),
    legend.position = "right"
  )


ggplot(mean_land_values, aes(x = Date, y = mean_land_value, color = region)) +
  geom_smooth(se = FALSE, size = 1.2) +
  labs(title = "Trend in Mean Land Value by Region Over Time",
    x = "Date",
    y = "Mean Land Value",
    color = "Region") +
  theme_minimal() +
  theme(text = element_text(size = 12), plot.title = element_text(face = "bold", hjust = 0.5))
  
  
## Exercise 2. Life expectancy and GDP per capita 1952-2007

gapminder %>%
  head() %>% 
  kable()
library(gapminder)

